apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: todo-frontend