{{- if .Values.secrets.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc }}
{{- end }}