{{- if .Values.secrets.openAiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openAiApiKey | b64enc }}
{{- end }}