{{- if and .Values.secrets.neonDbUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  neon-db-url: {{ .Values.secrets.neonDbUrl | b64enc }}
{{- end }}